In [7]:
#1. 주어진 1차원 배열을 2차원 배열로 변경하는 코드를 작성하세요.
# (numpy 모듈 사용하기, reshape 함수 사용하기)
# 출력 : [[2 4 6]
#         [8 9 15]]

# numpy 모듈 불러오기.
import numpy as np

vec = np.array([2,4,6,8,9,15])

# 코드를 완성해주세요.
two_dim_vec = vec.reshape(2, 3) 

print(two_dim_vec)

[[ 2  4  6]
 [ 8  9 15]]


In [3]:
# 2. numpy를 활용해 연립방정식을 풀어보자.
# (numpy의 역행렬 함수 np.linalg.inv()와 행렬곱 함수 사용)
import numpy as np
A = np.array([[2, 3], [5, 6]])
B = np.array([4, 5])
C = np.linalg.inv(A)
ans = np.dot(C, B)
print(ans)

[-3.          3.33333333]


In [4]:
# 2. numpy를 활용해 연립방정식을 풀어보자.
# (numpy의 역행렬 함수 np.linalg.inv()와 행렬곱 함수 사용)
import numpy as np
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]])
B = np.array([0, 9, 8])
C = np.linalg.inv(A)
ans = np.dot(C, B)
print(ans)

[1. 2. 3.]


In [ ]:
# 3. 24명의 인원을 받아 진행되는 프로그램이 있다.
# 지원한 순서대로 N명씩 M팀으로 나누어 프로그램을 진행하려고 한다.
# 지원한 순서대로 N명씩 묶어 M팀을 만든다고 할 때,
# 각 팀에서 제일 나이가 많은 사람과 제일 나이가 적은 사람의 나이를 출력하시요.
# 지원한 24명의 나이를 입력 받은 후, 몇 명으로 나눌지 N 값을 입력 받는다.
#( 첫 입력은 1차원 배열에 받고, 그 1차원 배열을 한 팀이 한 행에 들어가도록 배열을 재구성한다.)
# (N은 24의 약수이다. 입력되는 정수들은 나이를 의미하고, 공백으로 나누어 받는다.)
# (1<=나이<=100 이다.)

import numpy as np

age = list(map(int, input().split(' ')))
N = int(input())
M = 24 // N
vec1 = np.array(age)
vec2 = vec1.reshape(M, N)
print(vec2)

for i in range(M):
    print(vec2[i].max(), vec2[i].min())

<입력>
12 7 87 32 65 24 9 61 5 34 21 24 37 45 99 3 54 77 42 12 31 13 54 82
6
<출력>
87 7
61 5
99 3
82 12

**재 구성된 배열 형태
12 7 87 32 65 24
9 61 5 34 21 24
37 45 99 3 54 77
42 12 31 13 54 82


In [ ]:
import numpy as np
c = np.arange(1,10)
d = np.array(range(1,10))
print(c)
print(d)

In [5]:
import numpy as np
vec = np.random.random((3, 3, 3))
print(vec)

[[[0.42740366 0.77798575 0.64209089]
  [0.57229102 0.24768023 0.02149599]
  [0.56484639 0.42278291 0.00743365]]

 [[0.87044575 0.56317934 0.9271617 ]
  [0.21833309 0.0599338  0.97505603]
  [0.27946458 0.52457393 0.7784792 ]]

 [[0.73797087 0.50388892 0.01292724]
  [0.12708811 0.30170354 0.21416323]
  [0.30070852 0.89849866 0.72747317]]]


In [ ]:
import numpy as np
#import numpy.linalg as LA

A = np.array([[2, 3], [5, 6]])
B = np.array([4, 5])
C = np.linalg.inv(A)
ans = C.dot(B)
print(ans) #[x, y]

In [ ]:
import numpy as np

M = np.array(list(map(int, input().split())))
N = int(input())
M = M.reshape(-1, N)

for i in M:
    print(max(i), min(i))

In [8]:
import numpy as np

age = list(map(int,input().split()))
age = np.array(age)
N = int(input())
age = age.reshape(24//N,N)

for i in range(24//N):
    Max = np.max(age[i,:])
    Min = np.min(age[i,:])
    print(Max, Min)

[-3.          3.33333333]


In [6]:
import numpy as np

a = int(input())
prim = np.full((a,a), 0)
day = 1
rupee = 0

print(prim)
print(f"(day {day})")

while(a>2):
    prim[day:-day, day:-day] = day
    a = a - 2
    rupee += (a**2) * 100
    day += 1
    
    print(prim)
    print(f"(day {day})")
    print(f"({rupee} rupee)")
    
    

3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
(day 1)
[[0 0 0]
 [0 1 0]
 [0 0 0]]
(day 2)
(100 rupee)


In [1]:
N, M = map(int, input().split(' '))
print(N, M)

6 4
6 4


In [40]:
import numpy as np


a = list(map(int,input().split()))
a = np.array(a)

arr = list(map(int,input().split(' ')))

arr = np.array(arr).reshape((N, M))

n = a[0]//2  # 2
m = a[1]//2  # 3

arr = np.vsplit(arr,n)

h = np.zeros((6, 2, 2))

idx = 0
for i in range(0,n): # 0 1
    re = np.hsplit(arr[i],m)
    
    for j in range(0, m): # 0 1 2  3 4 5
        h[idx] = re[i*m + j]
        idx += 1
        
        
max = 0
for i in range(0, N):
    if np.sum(h[i]) > max:
        max = np.sum(h[i])
        
print(int(max))

4 6
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24


ValueError: array split does not result in an equal division

In [23]:
idx = 0
for i in range(0,n): # 0 1 2
    re = np.hsplit(arr[i],m)
    h[idx] = re[0]
    idx += 1
    h[idx] = re[1]
    idx += 1
        
        
max = 0
for i in range(0, 6):
    if np.sum(h[i]) > max:
        max = np.sum(h[i])
    
print(max)
    
# print(re)
# np.max(s_arr)

# for i in range(0,n-1):
#     k=np.append(h[i],h[i+1],axis=0)
#     print(k)

NameError: name 'N' is not defined

In [60]:
import pandas as pd
import numpy as np
exam = pd.read_csv('exam.csv')

In [61]:
exam

id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [63]:
# 과학 과목에 대한 평균을 구하고 출력하라
print('원래 과학 평균 : ', exam['science'].mean())

원래 과학 평균 :  59.45


In [64]:
exam.loc[[3,7,12],['science']] = np.nan

In [65]:
exam

id  nclass  math  english  science
0    1       1    50       98     50.0
1    2       1    60       97     60.0
2    3       1    45       86     78.0
3    4       1    30       98      NaN
4    5       2    25       80     65.0
5    6       2    50       89     98.0
6    7       2    80       90     45.0
7    8       2    90       78      NaN
8    9       3    20       98     15.0
9   10       3    50       98     45.0
10  11       3    65       65     65.0
11  12       3    45       85     32.0
12  13       4    46       98      NaN
13  14       4    48       87     12.0
14  15       4    75       56     78.0
15  16       4    58       98     65.0
16  17       5    65       68     98.0
17  18       5    80       78     90.0
18  19       5    89       68     87.0
19  20       5    78       83     58.0

In [72]:
# # nan 값이 입력된 상태에서 과학의 평균을 구하라
# print('nan 값 입력 후 평균 : ', exam['science'].mean())

In [68]:
exam['science'] = exam['science'].fillna(0) #fillna na값을 채운다.
print('nan 값을 0으로 대체한 평균 : ', exam['science'].mean())

nan 값을 0으로 대체한 평균 :  52.05


In [73]:
exam.loc[[3,7,12],['science']] = np.nan
# nan 값이 삽입되기 전 상태에서 구한 과학 점수의 평균을
# 소수점 1의 자리에서 반올림한 수치를 구하고
# 해당 수치로 NaN 자리를 대체하라
exam['science'] = exam['science'].fillna(59) #fillna na값을 채운다.

In [74]:
exam['science'].mean()

60.9

In [57]:
# nan 값을 0으로 대체 했을 때의 과학 과목의 평균과
# nan 값을 삽입하기 전에 구한 과학 과목의 평균을 NaN 값 대신에 삽입했을 때의 평균
# 을 확인하고,
# 각각의 평균값을 원래의 데이터에서의 과학 과목 평균 수치와 비교해본다.
# 수치적으로 차이가 나는 이유를 간략히 설명하세요.

61.2