In [17]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'ID':[20190103, 20190222, 20190531],
                             'name':['Kim', 'Lee', 'Jeong'],
                             'class':['H', 'W', 'S']})
sr = pd.Series({'ID':19011675, 'name':'Jo','class':'J'})

In [14]:
print(df)

         ID   name class
0  20190103    Kim     H
1  20190222    Lee     W
2  20190531  Jeong     S


In [18]:
print(sr)

ID       19011675
name           Jo
class           J
dtype: object


In [19]:
add_data = df.add(sr, axis = 1)

In [20]:
print(add_data)

         ID     name class
0  39201778    KimJo    HJ
1  39201897    LeeJo    WJ
2  39202206  JeongJo    SJ


In [29]:
df = pd.DataFrame({'ID':[20190103, 20190222, 20190531],
                             'name':['Kim', 'Lee', 'Jeong'],
                             'class':['H', 'W', 'S']})
print(df)
print(df.iloc[:2, :2])

         ID   name class
0  20190103    Kim     H
1  20190222    Lee     W
2  20190531  Jeong     S
         ID name
0  20190103  Kim
1  20190222  Lee


In [43]:
sr1 = pd.Series({'ID':19011675, 'name':'Jo','class':'J'})
sr2 = pd.Series({'ID':18080808080, 'name':'Hyun','class':'P', 'trial' : 0})

In [44]:
print(sr1)

ID       19011675
name           Jo
class           J
dtype: object


In [45]:
print(sr2)

ID       18080808080
name            Hyun
class              P
trial              0
dtype: object


In [46]:
sradd = sr1.add(sr2)

In [47]:
print(sradd)

ID       18099819755
class             JP
name          JoHyun
trial            NaN
dtype: object


In [48]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [49]:
arr[[0,1],:]=arr[[1,0],:]

In [50]:
print(arr)

[[4 5 6]
 [1 2 3]]


In [70]:
import pandas as pd

friend_list = [
['name',['John', 'Jenny', 'Nate']],
['age', [20,30,30]],
['job',['student', 'developer', 'teacher']]
] 

df = pd.DataFrame.from_dict(dict(friend_list))

print(df)

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher


In [76]:
df[(df['age'] > 25) & (df['name'] == 'Nate')]

name  age      job
2  Nate   30  teacher